USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE SNOWFLAKE_ECOMMERCE;
CREATE OR REPLACE SCHEMA SCHEMA_ECOMMERCE;
USE SNOWFLAKE_ECOMMERCE;
USE SCHEMA SCHEMA_ECOMMERCE;
CREATE OR REPLACE  TABLE CUSTOMER (
   ID                   NUMBER                  ,
   FIRSTNAME            VARCHAR(40)         NOT NULL,
   LASTNAME             VARCHAR(40)         NOT NULL,
   CITY                 VARCHAR(40)         NULL,
   COUNTRY              VARCHAR(40)         NULL,
   PHONE                VARCHAR(20)         NULL,
  PRIMARY KEY (ID)
);

CREATE OR REPLACE  TABLE "ORDER" (
   ID                   NUMBER                  ,
   ORDERDATE            DATETIME             NOT NULL DEFAULT CURRENT_TIMESTAMP,
   ORDERNUMBER          VARCHAR(10)         NULL,
   CUSTOMERID           NUMBER                  NOT NULL,
   TOTALAMOUNT          DECIMAL(12,2)        NULL DEFAULT 0,
   PRIMARY KEY (ID)
);

CREATE OR REPLACE  TABLE ORDERITEM (
   ID                   NUMBER                  ,
   ORDERID              NUMBER                  NOT NULL,
   PRODUCTID            NUMBER                  NOT NULL,
   UNITPRICE            DECIMAL(12,2)        NOT NULL DEFAULT 0,
   QUANTITY             NUMBER                  NOT NULL DEFAULT 1,
     PRIMARY KEY (ID)
);

CREATE OR REPLACE  TABLE PRODUCT (
   ID                   NUMBER                  ,
   PRODUCTNAME          VARCHAR(50)         NOT NULL,
   SUPPLIERID           NUMBER                  NOT NULL,
   UNITPRICE            DECIMAL(12,2)        NULL DEFAULT 0,
   PACKAGE              VARCHAR(30)         NULL,
   ISDISCONTINUED       INT                  NOT NULL DEFAULT 0,
     PRIMARY KEY (ID)
);

CREATE OR REPLACE  TABLE SUPPLIER (
   ID                   NUMBER                  ,
   COMPANYNAME          VARCHAR(40)         NOT NULL,
   CONTACTNAME          VARCHAR(50)         NULL,
   CONTACTTITLE         VARCHAR(40)         NULL,
   CITY                 VARCHAR(40)         NULL,
   COUNTRY              VARCHAR(40)         NULL,
   PHONE                VARCHAR(30)         NULL,
   FAX                  VARCHAR(30)         NULL,
     PRIMARY KEY (ID)
);


ALTER TABLE "ORDER" ADD FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(ID);

ALTER TABLE ORDERITEM ADD FOREIGN KEY (ORDERID) REFERENCES "ORDER"(ID);

ALTER TABLE ORDERITEM ADD FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(ID);

ALTER TABLE PRODUCT ADD FOREIGN KEY (SUPPLIERID) REFERENCES SUPPLIER(ID);

COMMIT;
--------------------------------------------------STAGE & FILE FORMAT DDLS-----------------------------

CREATE STAGE INTERNAL_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COPY_OPTIONS = (ON_ERROR='SKIP_FILE');
  
CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = CSV
RECORD_DELIMITER = '\n'
FIELD_DELIMITER = ','
SKIP_BLANK_LINES = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
TIMESTAMP_FORMAT='MON DD YYYY HH12:MI:SS AM'
FIELD_OPTIONALLY_ENCLOSED_BY='\''
SKIP_HEADER = 1
COMMENT = 'File Foramt to load CSV Files with headers';


--------------------PIPE RELATED DDLS------------------------------------------------------------------

CREATE PIPE SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE.CSV_ORDER_PIPE IF NOT EXISTS AS COPY INTO "ORDER" FROM @INTERNAL_STAGE FILE_FORMAT=(FORMAT_NAME=CSV_FILE_FORMAT);
ALTER PIPE SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE.CSV_ORDER_PIPE SET PIPE_EXECUTION_PAUSED=TRUE;
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE SNOWPIPE;
GRANT ROLE SNOWPIPE TO ROLE SECURITYADMIN;
USE ROLE SYSADMIN;
USE SCHEMA SCHEMA_ECOMMERCE;
GRANT USAGE ON DATABASE SNOWFLAKE_ECOMMERCE TO ROLE SNOWPIPE;
GRANT USAGE ON SCHEMA SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE TO ROLE SNOWPIPE;
GRANT INSERT, SELECT ON SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE."ORDER" TO ROLE SNOWPIPE;
GRANT WRITE, READ ON STAGE SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE.INTERNAL_STAGE TO ROLE SNOWPIPE;
GRANT OWNERSHIP ON PIPE SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE.CSV_ORDER_PIPE TO ROLE SNOWPIPE;
GRANT USAGE ON FILE FORMAT SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE.CSV_FILE_FORMAT TO ROLE SNOWPIPE;
USE ROLE SECURITYADMIN;
CREATE USER SNOWPIPE;
GRANT ROLE SNOWPIPE TO USER SNOWPIPE;
ALTER USER SNOWPIPE SET DEFAULT_ROLE = SNOWPIPE;
ALTER USER SNOWPIPE SET PASSWORD = 'Snowflake123';
ALTER USER SNOWPIPE SET RSA_PUBLIC_KEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0QgPNLQuehPmf1bVlXMZ
h7bvWQyMES0tALl/Xtz1lKPTPqO7IvxfgG0Vd7B2tWIAsJod/ugyV5kIqpEuZsif
/5QxLSICcMdKUsAHCnOX14BV8609suOx4YwSobw3AZB3zOeQIAw1Qe5xBo9fGHhG
ukyAQjywkDJyIoNaw4OwAB3OAG+B7+D/Q5rgo8FW4GTwB0TjYYCjJmv+4MTJBfAO
3Fj7rccNXt4nZloXMg4MJlm7gF0qDf4xVx+85VYzyvV2fzaGiEApqoLEvO1zIYla
KKhRGzCUk/RnbnEZTkKJ+TkL46N/mjcmmHeC01M8hAhzW/bKMkxEt58ko3zUqIw/
aQIDAQAB';

ALTER PIPE SNOWFLAKE_ECOMMERCE.SCHEMA_ECOMMERCE.CSV_ORDER_PIPE SET PIPE_EXECUTION_PAUSED=FALSE;
SELECT SYSTEM$PIPE_FORCE_RESUME('CSV_ORDER_PIPE');

------------------------CLEANUP PROJECT---------------------------------------------------------
USE ROLE SYSADMIN;
USE SNOWFLAKE_ECOMMERCE;
USE SCHEMA SCHEMA_ECOMMERCE;
DROP STAGE INTERNAL_STAGE;  
DROP FILE FORMAT CSV_FILE_FORMAT;
DROP TABLE CUSTOMER;
DROP TABLE "ORDER";
DROP TABLE ORDERITEM;
DROP TABLE PRODUCT;
DROP TABLE SUPPLIER;
DROP SCHEMA SCHEMA_ECOMMERCE;
DROP DATABASE SNOWFLAKE_ECOMMERCE;

USE ROLE SECURITYADMIN;
DROP ROLE SNOWPIPE;
DROP USER SNOWPIPE;